language: cpp
sudo: false
dist: trusty
matrix:
  include:
    - os: linux
      addons: &1
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - doxygen
            - g++-7
            - gfortran
            - gfortran-7
            - python-dev
            - libatlas-dev
            - liblapack-dev
            - liblapacke-dev
            - libopenmpi-dev
            - openmpi-bin
            - libboost1.55-all-dev
            - uuid-dev
            - pkg-config
      env:
        - GENERATOR="Unix Makefiles"
        - BUILDFLAGS="VERBOSE=1"
        - LC_ALL="en_US.UTF-8"
        - LANG="en_US.UTF-8"
        - LANGUAGE="en_US.UTF-8"
        - PYTHONIOENCODING=UTF-8
    - os: linux
      addons: *1
      env:
        - GENERATOR="Ninja"
        - BUILDFLAGS="-v"
        - LC_ALL="en_US.UTF-8"
        - LANG="en_US.UTF-8"
        - LANGUAGE="en_US.UTF-8"
        - PYTHONIOENCODING=UTF-8
    - os: osx
      env:
        - GENERATOR="Unix Makefiles"
        - BUILDFLAGS="VERBOSE=1"
    - os: osx
      env:
        - GENERATOR="Ninja"
        - BUILDFLAGS="-v"

cache:
  pip: true
  directories:
    - $HOME/Deps/cmake
    - $HOME/Deps/eigen
    - $HOME/Deps/hdf5
    - $HOME/Deps/ninja
    - $HOME/Deps/conda

env:
  global:
    - PATH=$HOME/Deps/cmake/bin${PATH:+:$PATH}
    - PATH=$HOME/Deps/ninja${PATH:+:$PATH}
    - LD_LIBRARY_PATH=$HOME/Deps/hdf5/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}

before_install:
  # Dependencies are downloaded in $HOME/Downloads and installed in $HOME/Deps
  - mkdir -p $HOME/Downloads $HOME/Deps

install:
  - ./dependencies/install_dependencies.sh
  - pipenv install
  - pipenv run python --version

before_script:
  - test -n $CC && unset CC
  - test -n $CXX && unset CXX
  - test -n $FC && unset FC

script:
  - ./dependencies/report_versions.sh
  - pipenv run python testing/collect_tests.py 'Chapter*/recipe-*'
  - pipenv run python testing/collect_tests.py 'to-triage/recipe-*'
